-- Create USER_CREDENTIALS table
CREATE TABLE USER_CREDENTIALS (
    UserID SERIAL PRIMARY KEY,
    UserEmail VARCHAR(255) UNIQUE NOT NULL,
    UserPassword VARCHAR(255) NOT NULL,
    UserAccess VARCHAR(50) DEFAULT 'Default' CHECK (UserAccess IN ('Admin', 'Default')),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Create TERM table
-- TermID format: 'CS1'–'CS8', 'IT1'–'IT8'
CREATE TABLE TERM (
    TermID VARCHAR(4) PRIMARY KEY,
    ProgramID VARCHAR(4) NOT NULL CHECK (ProgramID IN ('CS', 'IT')),
    YearLevel INT NOT NULL CHECK (YearLevel BETWEEN 1 AND 4),
    Semester INT NOT NULL CHECK (Semester IN (1, 2)),
    ReqUnits INT,
    UNIQUE(ProgramID, YearLevel, Semester)
);

-- Create USER_PROFILE table
CREATE TABLE USER_PROFILE (
    UserID INT PRIMARY KEY REFERENCES USER_CREDENTIALS(UserID) ON DELETE CASCADE,
    UserName VARCHAR(255) NOT NULL,
    TermID VARCHAR(4) REFERENCES TERM(TermID) ON DELETE SET NULL
);

-- Create COURSE table
-- CourseID format: up to 11 chars (e.g. 'CS1-CS101', 'IT3-IT301')
CREATE TABLE COURSE (
    CourseCode VARCHAR(11) PRIMARY KEY,
    TermID VARCHAR(4) NOT NULL REFERENCES TERM(TermID) ON DELETE CASCADE,
    CourseName VARCHAR(255) NOT NULL,
    CourseUnits INT
);

-- Create PROFESSOR table
CREATE TABLE PROFESSOR (
    ProfID SERIAL PRIMARY KEY,
    ProfName VARCHAR(255) NOT NULL,
    ProfDepartment VARCHAR(255)
);

CREATE TABLE COURSESLOT (
    CourseSlotID SERIAL PRIMARY KEY,
    CourseCode VARCHAR(11) NOT NULL REFERENCES COURSE(CourseCode) ON DELETE CASCADE,
    ProfID INT REFERENCES PROFESSOR(ProfID) ON DELETE SET NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    ScheduleDay VARCHAR(50),
    RoomCode VARCHAR(20)
);
-- Create SCHEDULE table
CREATE TABLE SCHEDULE (
    ScheduleID SERIAL PRIMARY KEY,
    UserID INT NOT NULL REFERENCES USER_CREDENTIALS(UserID) ON DELETE CASCADE,
    ScheduleName VARCHAR(255) NOT NULL,
    ScheduleList JSONB DEFAULT '[]'::jsonb,
    TotalUnits INT DEFAULT 0,
    Regular BOOLEAN DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);