DROP TABLE IF EXISTS SCHEDULE CASCADE;
DROP TABLE IF EXISTS COURSESLOT CASCADE;
DROP TABLE IF EXISTS COURSE CASCADE;
DROP TABLE IF EXISTS PROFESSOR CASCADE;
DROP TABLE IF EXISTS USER_PROFILE CASCADE;
DROP TABLE IF EXISTS TERM CASCADE;
DROP TABLE IF EXISTS PROGRAM CASCADE;
DROP TABLE IF EXISTS USER_CREDENTIALS CASCADE;

-- Create USER_CREDENTIALS table
CREATE TABLE USER_CREDENTIALS (
    UserID SERIAL PRIMARY KEY,
    UserEmail VARCHAR(255) UNIQUE NOT NULL,
    UserPassword VARCHAR(255) NOT NULL,
    UserAccess VARCHAR(50) DEFAULT 'Default' CHECK (UserAccess IN ('Admin', 'Default')),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Create PROGRAM table
CREATE TABLE PROGRAM (
    ProgramID VARCHAR(10) PRIMARY KEY,
    ProgramName VARCHAR(255) NOT NULL,
    TotalYears INT NOT NULL CHECK (TotalYears BETWEEN 1 AND 6),
    SemesterType INT NOT NULL CHECK (SemesterType IN (1, 2, 3)), -- 1 = 1 semester; 2 = 2 semesters; 3 = summer term
    DefaultUnits INT NOT NULL DEFAULT 18 CHECK (DefaultUnits BETWEEN 1 AND 40)
);


-- Create TERM table
CREATE TABLE TERM (
    TermID VARCHAR(10) PRIMARY KEY,
    ProgramID VARCHAR(10) NOT NULL REFERENCES PROGRAM(ProgramID) ON DELETE CASCADE,
    YearLevel INT NOT NULL CHECK (YearLevel BETWEEN 1 AND 6),
    Semester INT NOT NULL CHECK (Semester BETWEEN 1 AND 3),
    ReqUnits INT,
    UNIQUE(ProgramID, YearLevel, Semester)
);

-- Create USER_PROFILE table
CREATE TABLE USER_PROFILE (
    UserID INT PRIMARY KEY REFERENCES USER_CREDENTIALS(UserID) ON DELETE CASCADE,
    UserName VARCHAR(255) NOT NULL,
    TermID VARCHAR(10) REFERENCES TERM(TermID) ON DELETE SET NULL
);

-- Create COURSE table
CREATE TABLE COURSE (
    CourseCode VARCHAR(15) PRIMARY KEY,
    TermID VARCHAR(10) NOT NULL REFERENCES TERM(TermID) ON DELETE CASCADE,
    CourseName VARCHAR(255) NOT NULL,
    CourseUnits INT
);

-- Create PROFESSOR table
CREATE TABLE PROFESSOR (
    ProfID SERIAL PRIMARY KEY,
    ProfName VARCHAR(255) NOT NULL,
    ProfDepartment VARCHAR(255)
);

CREATE TABLE COURSESLOT (
    CourseSlotID SERIAL PRIMARY KEY,
    CourseCode VARCHAR(15) NOT NULL REFERENCES COURSE(CourseCode) ON DELETE CASCADE,
    ProfID INT REFERENCES PROFESSOR(ProfID) ON DELETE SET NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    ScheduleDay VARCHAR(50),
    RoomCode VARCHAR(20)
);
-- Create SCHEDULE table
CREATE TABLE SCHEDULE (
    ScheduleID SERIAL PRIMARY KEY,
    UserID INT NOT NULL REFERENCES USER_CREDENTIALS(UserID) ON DELETE CASCADE,
    ScheduleName VARCHAR(255) NOT NULL,
    ScheduleList JSONB DEFAULT '[]'::jsonb,
    TotalUnits INT DEFAULT 0,
    Regular BOOLEAN DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);