apiVersion: v1
kind: ConfigMap
metadata:
  name: sched-builder-config
data:
  DB_USER: "postgres"
  DB_HOST: "localhost"  # Update to your PostgreSQL service name in K8s
  DB_NAME: "scheduler"
  DB_PORT: "5432"
  PORT: "3000"