apiVersion: v1
kind: Secret
metadata:
  name: sched-builder-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # postgres
  DB_HOST: bG9jYWxob3N0  # localhost (but in K8s, this might be a service name)
  DB_NAME: c2NoZWR1bGVy  # scheduler
  DB_PASSWORD: YnVpbGRlcjEyM2Nkag==  # builder123cdj
  DB_PORT: NTQzMg==  # 5432
  JWT_SECRET: MGUwN2VkOGI4MGMxMTZiZDQyYzMyY2Q3YjQ4Zjc0MmYyMmVlMTg0ZGQ0ZGYyZTViNjViZmVjYzMyMmFiYjBhNg==  # 0e07ed8b80c116bd42c32cd7b48f742f22ee184dd4df2e5b65bfecc322abb0a6
  PORT: MzAwMA==  # 3000